name: deploy-into-github-pages
on: [push]
jobs:
  deploy-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact
      - uses: actions/deploy-page
